name: Create PR to Main

on:
  push:
    branches:
      - 'Dev'

jobs:
  test-and-create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Importante para ter acesso a todo o histórico
      
      # Configuração específica para Next.js + TypeScript
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      # Verificação de tipos TypeScript
      - name: TypeScript check
        run: npm run type-check || npm run tsc || echo "Executando verificação de tipos TypeScript"
        
      # Build do projeto Next.js
      - name: Build Next.js application
        run: npm run build
      
      # Extrair alterações desde o último merge para Main
      - name: Get commits since last merge
        id: get_changes
        run: |
          LAST_MERGE=$(git log --merges --pretty=format:"%H" origin/main..origin/Dev | head -n 1)
          if [ -z "$LAST_MERGE" ]; then
            CHANGES=$(git log --pretty=format:"- %s (%h)" origin/main..origin/Dev)
          else
            CHANGES=$(git log --pretty=format:"- %s (%h)" $LAST_MERGE..origin/Dev)
          fi
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      # Criar Pull Request para Main
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Promoção Dev para Main"
          title: "🚀 Promoção Dev para Main ${{ steps.jira_tickets.outputs.tickets }}"
          body: |
            ## Solicitação de Promoção para Produção

            Este PR foi gerado automaticamente para promover as alterações da branch Dev para Main.

            ### 🔄 Alterações Incluídas
            ${{ steps.get_changes.outputs.changes }}

            ### ✅ Verificações
            - [x] Build Next.js executado com sucesso
            - [x] Verificação de tipos TypeScript
            - [x] Testes unitários executados
            - [ ] Revisão de código necessária
            - [ ] Testes em ambiente de homologação realizados

            ### 📋 Próximos passos
            1. Revisar as alterações
            2. Aprovar o PR
            3. Verificar deploy em produção
          base: main
          branch: automated-pr/dev-to-main
          labels: |
            automated
            promotion
            needs-review
            next-js

      # Adicionar revisores ao PR (opcional)
      - name: Add reviewers
        if: steps.create_pr.outputs.pull-request-number
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ steps.create_pr.outputs.pull-request-number }}
          body: |
            @tech-leads Por favor, revisem este PR de promoção para produção.
